### ISSUE TITLE
示例的评论框炸了

### ISSUE THREAD

**Issue by Mabbs** [discussjs/discuss#19]
评论后返回：MongoServerError: unknown top level operator: $gt. If you have a field name that starts with a '$' symbol, consider using $getField or $setField.

**Comment by lete114** [comment]
请提供更多可用信息，以上信息我无法复现，以及定位问题

**Comment by lete114** [comment]
我在本地使用最新版本进行测试，均无如上错误提示，你可以试着更新到最新版本

**Comment by Mabbs** [comment]
> 请提供更多可用信息，以上信息我无法复现，以及定位问题

![image](https://user-images.githubusercontent.com/17966333/198880995-b1438d83-5718-4397-b12e-95d0dc6e04a6.png)


> 我在本地使用最新版本进行测试，均无如上错误提示，你可以试着更新到最新版本

我是直接试的 <https://discuss.js.org/> 评论框报的错

**Comment by lete114** [comment]
问题已得到解决，感谢你的提问
https://github.com/discussjs/discuss/releases/tag/v1.1.10
