### ISSUE TITLE
建议别用jsdelivr

### ISSUE THREAD

**Issue by StarWEB890** [discussjs/discuss#9]
能否使用unpkg？不行的话staticaly也行啊

**Comment by lete114** [comment]
明确一下你的问题

**Comment by StarWEB890** [comment]
听人说jsdelivr会报408错误（其实我之前也有遇到过这个错误）

**Comment by lete114** [comment]
用jsdelivr是指文档中的js链接是jsdelivr的链接吗？

如果你不想用jsdelivr，本项目已经被 cdnjs 收录了，你可以使用 cdnjs 的国内镜像，如: [https://cdn.baomitu.com/discuss](https://cdn.baomitu.com/discuss)

**Comment by StarWEB890** [comment]
对的
jsdelivr报错如下（以aplayer为一个例子）：
![](https://git.poker/StarWEB890/TuChuang/blob/master/images/TIM_4KGGiN9UVM.1wuc3kfmjxl.webp?raw=true)

**Comment by StarWEB890** [comment]
如果可以的话建议使用unpkg（能使用最新版本）

**Comment by StarWEB890** [comment]
感谢乐特大佬，对不起刚刚太激动了（以至于我把issues搞成了PR）

**Comment by lete114** [comment]
> 如果可以的话建议使用unpkg（能使用最新版本）

[https://lib.baomitu.com/discuss/1.0.7/discuss.js](https://lib.baomitu.com/discuss/1.0.7/discuss.js)

**Comment by StarWEB890** [comment]
感谢大佬，对不起刚刚太激动打扰到你了哈
